version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - aws-training

  backend:
    build: ../aws-backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - aws-training
    environment:
      - spring.datasource.username=root
      - spring.datasource.password=mysql
      - spring.datasource.url=jdbc:mysql://mysql-server:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false

networks:
  aws-training:
    external: true
    name: "aws-training"
